FROM golang:1.18 AS builder

WORKDIR /app
COPY echo-cli/ .

RUN go mod init echo-cli && \
    go get -d -v && \
    go build -o /echo-cli

FROM gcr.io/distroless/base-debian10

COPY --from=builder /echo-cli /echo-cli

ENV ADDR=
ENTRYPOINT ["/echo-cli"]
