FROM golang:1.18 AS builder
WORKDIR /app
COPY echo-serv/ .
RUN go mod init echo-serv && go mod tidy
RUN go build -o echo-serv

FROM gcr.io/distroless/base-debian10
COPY --from=builder /app/echo-serv /
EXPOSE 8080
ENTRYPOINT ["/echo-serv"]